language: python

python:
 - "3.6"

install: 
 - pip install -e .
 - pip install googlemaps
 - pip install codecov
 - pip install pandas
 - pip install numpy

script: pytest
after_success:
 - codecov
