language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U unittest
  - pip install codecov
install:
  - pip install unittest
after_success:
  - codecov # submit coverage
